version: '3'

services:
  app:
    build: .
    image: nincodedo/ninbot:latest
    ports:
      - '8080:8090'
    env_file:
      - config/docker.env
    environment:
      LOGGING_FILE: ninbot.log
      LOGGING_LEVEL_COM_NINCRAFT: trace
      SERVER_TOMCAT_MAX_THREADS: 5
      SPRING_DATASOURCE_USERNAME: ninbot
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    healthcheck:
      test: curl --request GET --url http://localhost:8090/actuator/health || exit 1
      interval: 45s
      timeout: 10s
      retries: 5
  db:
    image: mysql:latest
    env_file:
      - config/docker.env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data-volume:/var/lib/mysql
volumes:
  mysql-data-volume: