management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  application:
    name: ninbot
  datasource:
    url: jdbc:mysql://localhost:3306/ninbot
  banner:
    location: classpath:ninbot-ascii-art.txt
logging:
  file:
    path: logs
    name: ninbot.log
  level:
    dev:
      nincodedo: INFO
    root: ERROR
nincodedo:
  releaseFilterClass: dev.nincodedo.ninbot.ocw.release.DegreesOfNinbot
  supporterCheckClass: dev.nincodedo.ninbot.ocw.NinbotSupporterCheck
