name: Create release on tag push
on:
  push:
    tags:
      - "*"
jobs:
  createRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          discussion_category_name: 'Releases'
  buildMaven:
    name: Build Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build, Test
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw clean verify -P git-commit,integration --no-transfer-progress
  buildDocker:
    name: Build Docker and Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_ACTIONS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/nincodedo/ninbot:latest
            ghcr.io/nincodedo/ninbot:${{ github.sha }}
  deployGKE:
    needs: [buildMaven, buildDocker]
    name: Deploy GKE
    runs-on: ubuntu-latest
    steps:
      - name: GKE Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GKE_JSON }}
      - name: GKE Get Credentials
        uses: google-github-actions/get-gke-credentials@v0.8.2
        with:
          cluster_name: ninbot-cluster
          location: us-central1-c
      - name: GKE Deploy
        run: kubectl set image deployment/ninbot ninbot=ghcr.io/nincodedo/ninbot:${{ github.sha }}
