on: pull_request
name: PR Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Cache local Maven repository
        uses: actions/cache@v2.1.7
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Package
        run: ./mvnw clean verify -P git-commit,integration --no-transfer-progress
      - name: GitHub Docker Action
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ secrets.PACKAGE_ACTIONS_TOKEN || github.token }}
