on: pull_request
name: PR Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v1
      with:
        java-version: '13'
    - name: Update permissions on mvnw
      run: chmod 700 mvnw
    - name: Package
      run: ./mvnw clean verify -P git-commit,integration --no-transfer-progress
    - name: Sonar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./mvnw sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=nincraft -Dsonar.branch.name=${{ github.ref }} --no-transfer-progress
    - name: GitHub Docker Action
      uses: matootie/github-docker@v1.0.1
      with:
         username: nincodedo
         personalAccessToken: ${{ secrets.GITHUB_PACKAGE_ACTIONS }}
