on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
name: Build and Deploy
jobs:
  buildMaven:
    name: Build Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v1
        if: github.event_name == 'pull_request'
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build, Test
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw clean verify -P git-commit,integration --no-transfer-progress
  buildDocker:
    name: Build Docker  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_ACTIONS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/nincodedo/ninbot:latest
            ghcr.io/nincodedo/ninbot:${{ github.sha }}
  deployGKE:
    if: github.ref == 'refs/heads/main'
    needs: [buildMaven, buildDocker]
    name: Deploy GKE
    runs-on: ubuntu-latest
    steps:
      - name: GKE Login
        uses: google-github-actions/get-gke-credentials@v0.7.0
        with:
          cluster_name: ninbot-cluster
          location: us-central1-c
          credentials: ${{ secrets.GKE_JSON }}
      - name: GKE Deploy
        run: kubectl set image deployment/ninbot ninbot=ghcr.io/nincodedo/ninbot:${{ github.sha }}
