on: push
name: Maven build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: LucaFeger/action-maven-cli@9d8f23af091bd6f5f0c05c942630939b6e53ce44
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: clean package sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=nincraft -Dsonar.branch.name=${{ github.ref }}
