on:
  push:
    branches:
      - main
name: Build and Deploy
env:
  GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
  GCLOUD_EMAIL: ${{ secrets.GCLOUD_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: ninbot
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Cache local Maven repository
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build, Test
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw clean verify -P git-commit,integration --no-transfer-progress
      - name: GitHub Docker Action
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ secrets.PACKAGE_ACTIONS_TOKEN }}
          tag: |
            latest
            ${{ github.sha }}
          containerRegistry: true
      - name: GKE Login
        uses: google-github-actions/get-gke-credentials@v0.3.0
        with:
          cluster_name: ninbot-cluster
          location: us-central1
          credentials: ${{ secrets.GKE_JSON }}
      - name: GKE Deploy
        run: kubectl set image deployment/ninbot ninbot=ghcr.io/nincodedo/ninbot:$GITHUB_SHA
