on: push
name: On push build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Update permissions on mvnw
      run: chmod 700 mvnw
    - name: Package
      run: ./mvnw clean package -P git-commit
    - name: Sonar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./mvnw sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=nincraft -Dsonar.branch.name=${{ github.ref }}
